### ISSUE TITLE
Docs have incorrect signature for convert method

### ISSUE THREAD

**Issue by avolkovi** [TrevorHinesley/carrierwave-audio#2]
In this commit https://github.com/TrevorHinesley/carrierwave-audio/commit/46eb3d84fc346c46952ac69d8c00219e673ee6bd#diff-df63423b67b0b8ba9b521f757b8ea475R18 the signature of the convert method was changed from `def convert output_format = :mp3, output_options = {}` to `def convert options={}`.

In the README the relevant piece of recommended code is: 
```
 version :mp3 do
    process :convert => [:mp3]

    def full_filename(for_file)
      "#{super.chomp(File.extname(super))}.mp3"
    end
  end
```

Which should now be:
```
 version :mp3 do
    process :convert => [output_format: :mp3]

    def full_filename(for_file)
      "#{super.chomp(File.extname(super))}.mp3"
    end
  end
```

or an error will be raised `TypeError: no implicit conversion of Symbol into Hash`

**Comment by TrevorHinesley** [comment]
Thank you! Fixed
